### ISSUE TITLE
Tamer4 Download links are down

### ISSUE THREAD

**Issue by jmarsh88** [TamerPlatform/TamerPlatform#10]
I've tried all the links in the master readme, but they appear to be down

**Google 403 Error Page:**
Google Drive: [https://bit.ly/AndroidTamer4-GD](http://bit.ly/AndroidTamer4-GD) 
(this link might go down if downloaded more then 500 times a day) [Direct Link](https://docs.google.com/uc?id=0B8yPzNmXhURwZllmX3NLQVJkTXc&export=download)

**Redirects to "Why use Sourceforge?" (https://sourceforge.net/create/):**
Sourceforge: [https://bit.ly/AndroidTamer4-SF](http://bit.ly/AndroidTamer4-SF) and [Direct Link](http://downloads.sourceforge.net/project/androidtamer/AndroidTamerv4/AndroidTamer4.ova)
Redirects to "Why use Sourceforge?" (https://sourceforge.net/create/)

**Comment by DanielB21-verifone** [comment]
Hi. Same issue here

**Comment by DanielB21-verifone** [comment]
Good day

When can this be resolved as the links still do not work.

**Comment by anantshri** [comment]
As i have clarified many times over blog. Tamer4 is eol i am working on tamer5 taking longer then expected coz underlsying landspcape has changed drastically and debian/ubuntu itself were trying to do stuff that i was working on. 

Hopefully in next 2 to 3 months next release of tamer toolkit (tamer vm) should be out
